### ISSUE TITLE
ensdomains additional packages

### ISSUE THREAD

**Issue by cehali** [Amxx/KitsuneWallet-ERC1836#4]
Hi, 
To build project I had to add additional ensdomains packages to kitsune-contracts:
"@ensdomains/dnssec-oracle": "^0.1.2",
"@ensdomains/buffer": "^0.0.10"

**Comment by Amxx** [comment]
`"@ensdomains/dnssec-oracle": "^0.1.2"` and `"@ensdomains/buffer": "^0.0.10"` are part of the `devDependencies` for kitsune-contracts' `package.json`. Should this be moved to `dependencies` ?

What version are you using ?

**Comment by Amxx** [comment]
This error was present in version 0.3.7 but is fixed in 0.3.8. branch master has been updated to 0.3.8
